version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./code:/var/www/html
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"  
    volumes:
      - ./code:/var/www/html

      
  mariadb:
    image: mariadb:10.7
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mariadb:/var/lib/mysql 
    environment:
      - MYSQL_ROOT_PASSWORD=pw
      - MYSQL_PASSWORD=pw
      - MYSQL_USER=szilard
      - MYSQL_DATABASE=dbname
      - MYSQL_ROOT_HOST=%
  